import React, { useEffect, useMemo, useState } from 'react';
import { html } from '../lib/html.js';
import { DEFAULT_API_BASE_URL } from '../config/runtime.js';
import { StructureForgeApiClient } from '../services/apiClient.js';

// Examples are convenience payloads only. The available capability list,
// descriptions, routes, and publication state come from the live /v1/tools
// catalog so the web page cannot silently drift into advertising stale tools.
const TOOL_EXAMPLES = {
  minecraft_content_package_generate: { target_version: '1.20.5', package_id: 'structuresmith:manual_demo', books: [{ name: 'field_notes', title: 'Field Notes', author: 'StructureSmith', pages: ['Generated from StructureForge.'] }], loot_tables: [{ name: 'evidence', table_id: 'structuresmith:chests/manual_demo', guaranteed: [{ id: 'minecraft:paper', count: 1 }] }], bindings: [{ type: 'book_as_guaranteed_loot', book: 'field_notes', loot_table: 'evidence' }], manifest: {} },
  minecraft_advancement_generate: { target_version: '1.20.5', advancement_id: 'structuresmith:manual/first_discovery', display: { title: 'First Discovery', description: 'Find your first StructureSmith evidence item.', icon: 'minecraft:compass', frame: 'task' }, criteria: { found_item: { trigger: 'minecraft:inventory_changed', conditions: {} } } },
  minecraft_tag_generate: { target_version: '1.21', tag_id: 'structuresmith:building_stone', registry: 'block', replace: false, values: ['minecraft:stone', 'minecraft:stone_bricks', 'minecraft:deepslate_bricks'] },
  minecraft_datapack_manifest_generate: { target_version: '1.20.5', description: 'StructureSmith manual datapack output' },
  minecraft_book_generate: { target_version: '1.20.5', title: 'Containment Log', author: 'StructureSmith', pages: ['Entry one', { text: 'Entry two', bold: true }] },
  minecraft_loot_table_generate: { target_version: '1.20.5', table_id: 'structuresmith:chests/manual_evidence', items: [{ id: 'minecraft:iron_ingot', weight: 4, min_count: 1, max_count: 3 }], guaranteed: [{ id: 'minecraft:paper', count: 1 }] },
  minecraft_recipe_generate: { target_version: '1.20.5', recipe_id: 'structuresmith:manual/stone_mix', type: 'crafting_shapeless', ingredients: ['minecraft:stone', 'minecraft:gravel'], result: { id: 'minecraft:cobblestone', count: 2 } },
  minecraft_registry_probe: { id: 'minecraft:chest', kind: 'item', id_policy: 'namespace' },
  minecraft_icon_assign: { subject: 'advancement', target_version: '1.20.5', mode: 'auto' },
  minecraft_version: { version: '1.20.5' },
};

function pretty(value) { return JSON.stringify(value, null, 2); }
function gateStatus(result) { if (result?.gate?.status) return result.gate.status; if (result?.accepted === true) return 'PASS'; if (result?.accepted === false) return 'FAIL'; if (result) return 'OK'; return 'IDLE'; }
function statusClass(status) { const normalized = String(status || '').toLowerCase(); if (normalized === 'pass' || normalized === 'ok') return 'manual-status-pass'; if (normalized === 'warn') return 'manual-status-warn'; if (normalized === 'fail' || normalized === 'error') return 'manual-status-fail'; if (normalized === 'running' || normalized === 'loading') return 'manual-status-running'; return ''; }
function labelFor(name) { return String(name || '').replace(/^minecraft_/, '').replace(/_generate$/, '').replaceAll('_', ' ').replace(/\b\w/g, (c) => c.toUpperCase()); }
function shortFor(tool) { const semantic = tool?.['x-structuresmith']?.icon?.semantic; if (semantic) return semantic.split('_').map((part) => part[0]).join('').slice(0, 3).toUpperCase(); return labelFor(tool?.name).split(' ').map((part) => part[0]).join('').slice(0, 3).toUpperCase(); }
function endpointPath(tool) { const endpoint = tool?.['x-structuresmith']?.publication?.canonical_endpoint; try { return new URL(endpoint).pathname; } catch { return ''; } }
function manualTools(catalog) {
  return (catalog?.tools || []).filter((tool) => { const publication = tool?.['x-structuresmith']?.publication; return publication?.manual_ui?.state === 'available' && publication?.manual_ui?.surface === 'manual_workbench' && publication?.publication_state !== 'internal_unpublished'; }).map((tool) => ({ name: tool.name, id: tool.name, label: labelFor(tool.name), short: shortFor(tool), endpoint: endpointPath(tool), method: tool?.['x-structuresmith']?.publication?.http_method || 'POST', description: tool.description || '', example: TOOL_EXAMPLES[tool.name] || {} })).filter((tool) => tool.endpoint).sort((a, b) => a.label.localeCompare(b.label));
}

export function ManualCapabilityWorkbench() {
  const [apiBase, setApiBase] = useState(DEFAULT_API_BASE_URL); const client = useMemo(() => new StructureForgeApiClient(apiBase), [apiBase]);
  const [tools, setTools] = useState([]); const [activeId, setActiveId] = useState(''); const [requestText, setRequestText] = useState('{}'); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [runState, setRunState] = useState('LOADING');
  useEffect(() => { const controller = new AbortController(); setRunState('LOADING'); setError(''); client.tools(controller.signal).then((catalog) => { const discovered = manualTools(catalog); setTools(discovered); if (!discovered.length) { setActiveId(''); setRequestText('{}'); setRunState('IDLE'); return; } const first = discovered.find((tool) => tool.id === activeId) || discovered[0]; setActiveId(first.id); setRequestText(pretty(first.example)); setRunState('IDLE'); }).catch((loadError) => { if (loadError.name === 'AbortError') return; setTools([]); setError(`Could not load the live tool catalog: ${loadError.message || String(loadError)}`); setRunState('ERROR'); }); return () => controller.abort(); }, [client]);
  const activeTool = tools.find((tool) => tool.id === activeId) || tools[0] || null;
  const selectTool = (tool) => { setActiveId(tool.id); setRequestText(pretty(tool.example)); setResult(null); setError(''); setRunState('IDLE'); };
  const resetExample = () => { if (!activeTool) return; setRequestText(pretty(activeTool.example)); setResult(null); setError(''); setRunState('IDLE'); };
  const execute = async () => { if (!activeTool) return; setError(''); setResult(null); setRunState('RUNNING'); try { const body = JSON.parse(requestText); const response = await client.request(activeTool.endpoint, { method: activeTool.method, body }); setResult(response); setRunState(gateStatus(response)); } catch (executionError) { setError(executionError.message || String(executionError)); setRunState('ERROR'); } };
  const copyResult = async () => { if (!result || !navigator.clipboard) return; await navigator.clipboard.writeText(pretty(result)); };
  const findingCount = result?.gate?.findings?.length || 0;
  return html`
    <section className="manual-workbench" aria-label="Manual StructureSmith capability tools">
      <div className="manual-workbench-heading"><div><span className="eyebrow">Direct manual API access</span><div className="manual-title-row"><h2>Manual Capability Workbench</h2><span className="manual-count">${tools.length} live tools</span></div><p>The selector is generated from the live /v1/tools publication catalog. StructureForge does not maintain a separate advertised capability list.</p></div><label className="manual-api-field"><span>Executable API base URL</span><input value=${apiBase} onChange=${(event) => setApiBase(event.target.value)} /></label></div>
      ${!activeTool && html`<div className="manual-error" role="status"><strong>No published manual tools loaded</strong><span>${error || 'The live API did not advertise any capabilities for the manual_workbench surface.'}</span></div>`}
      ${activeTool && html`<div className="manual-tool-strip" role="tablist" aria-label="Manual capability selector">${tools.map((tool) => html`<button key=${tool.id} type="button" role="tab" aria-selected=${tool.id === activeId} className=${`manual-tool-button ${tool.id === activeId ? 'active' : ''}`} onClick=${() => selectTool(tool)}><span className="manual-tool-icon">${tool.short}</span><span className="manual-tool-label">${tool.label}</span></button>`)}</div><div className="manual-editor-shell"><div className="manual-editor-pane"><div className="manual-pane-heading"><div><span className="manual-endpoint">${activeTool.method} ${activeTool.endpoint}</span><h3>${activeTool.label}</h3><p>${activeTool.description}</p></div><button type="button" className="secondary" onClick=${resetExample}>Reset example</button></div><label className="manual-json-label" htmlFor="manual-request-json">Request JSON</label><textarea id="manual-request-json" className="manual-json-editor" spellCheck=${false} value=${requestText} onChange=${(event) => setRequestText(event.target.value)}></textarea><div className="manual-run-row"><button type="button" className="primary" disabled=${runState === 'RUNNING'} onClick=${execute}>${runState === 'RUNNING' ? 'Executing…' : `Run ${activeTool.label}`}</button><span className=${`manual-run-status ${statusClass(runState)}`}>${runState}</span><span className="manual-endpoint-note">Calls the same canonical HTTPS endpoint advertised to AI clients.</span></div></div><div className="manual-result-pane"><div className="manual-result-heading"><div><span className="eyebrow">Response + public gates</span><h3>Result</h3></div><div className="manual-result-actions">${findingCount > 0 && html`<span className="manual-finding-count">${findingCount} findings</span>`}<button type="button" className="secondary" disabled=${!result} onClick=${copyResult}>Copy result</button></div></div>${error && html`<div className="manual-error" role="alert"><strong>Request failed</strong><span>${error}</span></div>`}${!error && !result && html`<div className="manual-result-empty"><strong>Ready for manual execution</strong><span>The complete JSON artifact and gate report will appear here.</span></div>`}${result && html`<pre className="manual-result-json">${pretty(result)}</pre>`}</div></div>`}
    </section>`;
}
